# Generated by Django 5.2 on 2025-08-05 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DroughtAlertLevel',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('p_alert_desc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PestAlertLevel',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('p_alert_desc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity', models.IntegerField(default=0)),
                ('district', models.CharField(max_length=200)),
                ('location', models.IntegerField(default=0)),
                ('temp_max', models.IntegerField(default=0)),
                ('temp_min', models.IntegerField(default=0)),
                ('precip', models.IntegerField(default=0)),
                ('effect', models.IntegerField(default=0)),
                ('info', models.CharField(max_length=500)),
                ('actions', models.CharField(max_length=500)),
                ('drought_alert_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.droughtalertlevel')),
                ('pest_alert_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.pestalertlevel')),
            ],
        ),
    ]
