# Generated by Django 5.2 on 2025-08-05 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('commodity_desc', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='choice',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='choice',
            name='commodity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.commodity'),
        ),
    ]
