# Generated by Django 5.2 on 2025-08-05 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0002_commodity_alter_choice_id_alter_choice_commodity'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('commodity_desc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('commodity_desc', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='precip',
        ),
        migrations.AddField(
            model_name='choice',
            name='precip_max',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='choice',
            name='precip_min',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='choice',
            name='effect',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='choice',
            name='temp_max',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='choice',
            name='temp_min',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='commodity_desc',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='choice',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.location'),
        ),
    ]
