# Generated by Django 5.2 on 2025-08-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0003_district_location_remove_choice_precip_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commodity',
            new_name='CommodityType',
        ),
        migrations.RenameModel(
            old_name='Choice',
            new_name='Livestock',
        ),
        migrations.RenameField(
            model_name='livestock',
            old_name='commodity',
            new_name='commodity_name',
        ),
        migrations.RenameField(
            model_name='livestock',
            old_name='id',
            new_name='entry_id',
        ),
        migrations.RemoveField(
            model_name='district',
            name='commodity_desc',
        ),
        migrations.RemoveField(
            model_name='location',
            name='commodity_desc',
        ),
        migrations.AddField(
            model_name='location',
            name='commodit1y_desc',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
