# Generated by Django 5.2 on 2025-08-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0004_rename_commodity_commoditytype_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='commodit1y_desc',
            new_name='location_name',
        ),
        migrations.AddField(
            model_name='district',
            name='district_name',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
