# Generated by Django 5.2 on 2025-08-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0005_rename_commodit1y_desc_location_location_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
