# Generated by Django 5.2 on 2025-08-11 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0006_alter_district_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commoditytype',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='droughtalertlevel',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pestalertlevel',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
