# Generated by Django 5.2 on 2025-08-11 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0007_alter_commoditytype_id_alter_droughtalertlevel_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commoditytype',
            old_name='commodity_desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='district',
            old_name='district_name',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='droughtalertlevel',
            old_name='p_alert_desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='location_name',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='pestalertlevel',
            old_name='p_alert_desc',
            new_name='description',
        ),
    ]
