# Generated by Django 5.2.5 on 2025-08-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0008_rename_commodity_desc_commoditytype_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommodityCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=20)),
            ],
        ),
    ]
