# Generated by Django 5.2.5 on 2025-08-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0009_commoditycategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='commoditycategory',
            name='published_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='commoditycategory',
            name='updated_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
