# Generated by Django 5.2.5 on 2025-08-15 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0010_commoditycategory_published_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commoditytype',
            name='commodity_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commodity_category', to='agro.commoditycategory'),
        ),
        migrations.AddField(
            model_name='commoditytype',
            name='published_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='commoditytype',
            name='updated_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
