# Generated by Django 5.2.5 on 2025-08-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0011_commoditytype_commodity_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='published_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='updated_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
