# Generated by Django 5.2.5 on 2025-08-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0012_district_published_date_district_updated_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='droughtalertlevel',
            name='color_hex',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='droughtalertlevel',
            name='details',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='droughtalertlevel',
            name='published_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='droughtalertlevel',
            name='updated_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='pestalertlevel',
            name='color_hex',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='pestalertlevel',
            name='published_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='pestalertlevel',
            name='updated_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
