# Generated by Django 5.2.5 on 2025-08-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0013_droughtalertlevel_color_hex_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='droughtalertlevel',
            name='details',
        ),
        migrations.AddField(
            model_name='droughtalertlevel',
            name='action_level',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='droughtalertlevel',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='droughtalertlevel',
            name='description',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
