# Generated by Django 5.2.5 on 2025-08-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0014_remove_droughtalertlevel_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='droughtalertlevel',
            name='description',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
