# Generated by Django 5.2.5 on 2025-08-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0016_alter_commoditytype_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commoditytype',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
