# Generated by Django 5.2.5 on 2025-08-18 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0017_alter_commoditytype_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
                ('published_date', models.DateTimeField(auto_now=True, null=True)),
                ('updated_datetime', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='livestock',
            name='commodity_name',
        ),
        migrations.RemoveField(
            model_name='livestock',
            name='drought_alert_level',
        ),
        migrations.RemoveField(
            model_name='livestock',
            name='location',
        ),
        migrations.RemoveField(
            model_name='livestock',
            name='pest_alert_level',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Livestock',
        ),
    ]
