# Generated by Django 5.2.5 on 2025-08-18 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0018_zone_remove_livestock_commodity_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
