# Generated by Django 5.2.5 on 2025-08-18 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0019_alter_zone_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zone',
            old_name='description',
            new_name='zone_name',
        ),
    ]
