# Generated by Django 5.2.5 on 2025-08-19 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0020_rename_description_zone_zone_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='district',
            old_name='description',
            new_name='district_area',
        ),
    ]
