# Generated by Django 5.2.5 on 2025-08-19 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0021_rename_description_district_district_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='zone_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zone_id', to='agro.zone'),
        ),
    ]
