# Generated by Django 5.2.5 on 2025-08-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0022_district_zone_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='district_area',
            field=models.CharField(max_length=100),
        ),
    ]
