# Generated by Django 5.2.5 on 2025-08-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0023_alter_district_district_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Months',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('month_name', models.CharField(max_length=20)),
                ('published_date', models.DateTimeField(auto_now=True, null=True)),
                ('updated_datetime', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PestRiskEntry',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('month', models.IntegerField(default=0)),
                ('year', models.IntegerField(default=0)),
                ('commodity_id', models.IntegerField(default=0)),
                ('district_id', models.IntegerField(default=0)),
                ('pest_alert_lvl_id', models.IntegerField(default=0)),
                ('drought_alert_lvl_id', models.IntegerField(default=0)),
                ('temp_max', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('temp_min', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('precip_min', models.DecimalField(decimal_places=1, default=0.0, max_digits=20)),
                ('precip_max', models.DecimalField(decimal_places=1, default=0.0, max_digits=20)),
                ('effect', models.CharField(max_length=500)),
                ('info', models.CharField(max_length=500)),
                ('actions', models.CharField(max_length=500)),
                ('published_date', models.DateTimeField(auto_now=True, null=True)),
                ('updated_datetime', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
