# Generated by Django 5.2.5 on 2025-08-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0024_months_pestriskentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonalForecastAgriculture',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('month', models.IntegerField(default=0)),
                ('year', models.IntegerField(default=0)),
                ('commodity_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='pestriskentry',
            name='commodity_id',
        ),
        migrations.RemoveField(
            model_name='pestriskentry',
            name='month',
        ),
        migrations.RemoveField(
            model_name='pestriskentry',
            name='year',
        ),
    ]
