# Generated by Django 5.2.5 on 2025-08-21 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0025_seasonalforecastagriculture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PestRiskEntryStart',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('months', models.JSONField()),
                ('year', models.IntegerField(default=0)),
                ('commodity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.commoditytype')),
            ],
        ),
        migrations.DeleteModel(
            name='SeasonalForecastAgriculture',
        ),
    ]
