# Generated by Django 5.2.5 on 2025-08-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0026_pestriskentrystart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pestriskentrystart',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
