# Generated by Django 5.2.5 on 2025-08-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0027_alter_pestriskentrystart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='droughtalertlevel',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
