# Generated by Django 5.2.5 on 2025-08-21 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0030_alter_pestriskentrystart_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pestriskentry',
            name='pest_risk_start_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agro.pestriskentrystart'),
        ),
    ]
