# Generated by Django 5.2.5 on 2025-08-22 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0031_pestriskentry_pest_risk_start_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pestriskentry',
            name='drought_alert_lvl_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agro.droughtalertlevel'),
        ),
        migrations.AlterField(
            model_name='pestriskentry',
            name='pest_alert_lvl_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agro.pestalertlevel'),
        ),
    ]
