# Generated by Django 5.2.5 on 2025-08-22 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0033_pestriskeffect_alter_pestriskentry_effect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pestriskentry',
            name='district_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agro.district'),
        ),
    ]
