# Generated by Django 5.2.5 on 2025-08-22 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0034_alter_pestriskentry_district_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PestRiskAction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=300, null=True)),
                ('published_date', models.DateTimeField(auto_now=True, null=True)),
                ('updated_datetime', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='pestriskentry',
            name='actions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agro.pestriskaction'),
        ),
    ]
