# Generated by Django 5.2.5 on 2025-08-22 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0035_pestriskaction_alter_pestriskentry_actions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pestriskaction',
            old_name='description',
            new_name='action_description',
        ),
        migrations.RenameField(
            model_name='pestriskeffect',
            old_name='description',
            new_name='effect_description',
        ),
    ]
