# Generated by Django 5.2.5 on 2025-08-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0036_rename_description_pestriskaction_action_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pestriskaction',
            name='action_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='pestriskeffect',
            name='effect_description',
            field=models.TextField(null=True),
        ),
    ]
