# Generated by Django 5.2.5 on 2025-08-22 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0037_alter_pestriskaction_action_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pestriskentry',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
