# Generated by Django 5.2.5 on 2025-09-02 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0038_alter_pestriskentry_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pestriskentry',
            name='pest_risk_start_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pest_risk_entries', to='agro.pestriskentrystart'),
        ),
    ]
