# Generated by Django 5.2.5 on 2025-09-02 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0039_alter_pestriskentry_pest_risk_start_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PestRiskEntry',
            new_name='PestRiskEntryDetails',
        ),
        migrations.RenameModel(
            old_name='PestRiskEntryStart',
            new_name='PestRiskEntryMainListing',
        ),
        migrations.RenameField(
            model_name='pestriskentrydetails',
            old_name='pest_risk_start_id',
            new_name='pest_risk_listing_id',
        ),
    ]
