# Generated by Django 5.2.5 on 2025-09-03 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0040_rename_pestriskentry_pestriskentrydetails_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pestriskentrymainlisting',
            name='commodity_id',
        ),
        migrations.AddField(
            model_name='pestriskentrymainlisting',
            name='commodity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Commodity', to='agro.commoditytype'),
        ),
    ]
